<!--<h1><?php echo $this->translate('Sign In'); ?></h1>-->

<?php

$this->headScript()
	 ->prependFile($this->basePath().'/lib/validation-engine/js/languages/validation-engine-fr.js')
	 ->prependFile($this->basePath().'/lib/validation-engine/js/validation-engine.js')

?>


<?php

$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

?>

<?php echo $this->form(null, null)->openTag($form) ?>

	<img class="center-block" src="/img/logo2.png" />

	<div class="modal" style="display:block;position:relative;">
		<div class="modal-dialog" style="width:auto;">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">Connectez-vous à votre compte</h4>
				</div>
				<div class="modal-body" style="padding:25px 15px 0;">
					<div class="row">
						<div class="form-group col-md-12">
							<?php //echo $this->formLabel($form->get('identity')) ?>
							<?php echo $this->formInput($form->get('identity')) ?>
						</div>
						<div class="form-group col-md-12">
							<?php //echo $this->formLabel($form->get('credential')) ?>
							<?php echo $this->formInput($form->get('credential')) ?>
						</div>
						<?php if($this->formElementErrors($form->get('identity'))): ?>
						<div class="form-group col-md-12">
							<?php echo $this->formElementErrors($form->get('identity')); ?>
						</div>
						<?php endif; ?>
					</div>
				</div>
				<div class="modal-footer" style="margin:0;padding:15px;">
					<?php echo $this->formButton($form->get('submit')) ?>
					<?php if($this->redirect): ?>
					<input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
					<?php endif ?>
				</div>
			</div>
		</div>
	</div>


<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>

<script type="text/javascript">

$(function()
{
	$('[name=identity]').focus();

	$('form').validationEngine({promptPosition : "topLeft"});
});

</script>